<?php
/**
 * @var Formularium\Api\Representation\FormRepresentation $formulariumForm
 * @var Laminas\Form\Form $form
 * @var Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 */
?>
<div class="formularium-resource-page-block-layout-formularium-form">
    <?php if ($title = $formulariumForm->resourcePageBlockTitle()): ?>
        <h2 class="formularium-resource-page-block-layout-formularium-form__title"><?= $this->escapeHtml($title) ?></h2>
    <?php endif; ?>

    <?= $this->partial('formularium/common/formularium-form', ['form' => $form, 'formulariumForm' => $formulariumForm]); ?>
</div>
