<?php

namespace DoctrineProxies\__CG__\Formularium\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FormulariumFormSubmission extends \Formularium\Entity\FormulariumFormSubmission implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'form', 'site', 'sitePage', 'sitePageBlock', 'submitter', 'handler', 'submitted', 'handled', 'data', 'files'];
        }

        return ['__isInitialized__', 'id', 'form', 'site', 'sitePage', 'sitePageBlock', 'submitter', 'handler', 'submitted', 'handled', 'data', 'files'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FormulariumFormSubmission $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getForm(): \Formularium\Entity\FormulariumForm
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getForm', []);

        return parent::getForm();
    }

    /**
     * {@inheritDoc}
     */
    public function setForm(\Formularium\Entity\FormulariumForm $form): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setForm', [$form]);

        parent::setForm($form);
    }

    /**
     * {@inheritDoc}
     */
    public function getSite(): ?\Omeka\Entity\Site
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSite', []);

        return parent::getSite();
    }

    /**
     * {@inheritDoc}
     */
    public function setSite(\Omeka\Entity\Site $site): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSite', [$site]);

        parent::setSite($site);
    }

    /**
     * {@inheritDoc}
     */
    public function getSitePage(): ?\Omeka\Entity\SitePage
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSitePage', []);

        return parent::getSitePage();
    }

    /**
     * {@inheritDoc}
     */
    public function setSitePage(\Omeka\Entity\SitePage $sitePage): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSitePage', [$sitePage]);

        parent::setSitePage($sitePage);
    }

    /**
     * {@inheritDoc}
     */
    public function getSitePageBlock(): ?\Omeka\Entity\SitePageBlock
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSitePageBlock', []);

        return parent::getSitePageBlock();
    }

    /**
     * {@inheritDoc}
     */
    public function setSitePageBlock(\Omeka\Entity\SitePageBlock $sitePageBlock): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSitePageBlock', [$sitePageBlock]);

        parent::setSitePageBlock($sitePageBlock);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubmitter(): ?\Omeka\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubmitter', []);

        return parent::getSubmitter();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubmitter(?\Omeka\Entity\User $submitter): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubmitter', [$submitter]);

        parent::setSubmitter($submitter);
    }

    /**
     * {@inheritDoc}
     */
    public function getHandler(): ?\Omeka\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHandler', []);

        return parent::getHandler();
    }

    /**
     * {@inheritDoc}
     */
    public function setHandler(?\Omeka\Entity\User $handler): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHandler', [$handler]);

        parent::setHandler($handler);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubmitted(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubmitted', []);

        return parent::getSubmitted();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubmitted(\DateTime $submitted): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubmitted', [$submitted]);

        parent::setSubmitted($submitted);
    }

    /**
     * {@inheritDoc}
     */
    public function getHandled(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHandled', []);

        return parent::getHandled();
    }

    /**
     * {@inheritDoc}
     */
    public function setHandled(?\DateTime $handled): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHandled', [$handled]);

        parent::setHandled($handled);
    }

    /**
     * {@inheritDoc}
     */
    public function getData(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', []);

        return parent::getData();
    }

    /**
     * {@inheritDoc}
     */
    public function setData(array $data): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', [$data]);

        parent::setData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getFiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFiles', []);

        return parent::getFiles();
    }

    /**
     * {@inheritDoc}
     */
    public function getResourceId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResourceId', []);

        return parent::getResourceId();
    }

}
