<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var Formularium\Api\Representation\FormRepresentation[] $forms
 */

$this->htmlElement('body')->appendAttribute('class', 'formularium formularium-form browse');
?>

<?= $this->pageTitle($this->translate('Forms'), 1, $this->translate('Formularium')) ?>

<?php echo $this->searchFilters(); ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->browse()->renderSortSelector('formularium_forms'); ?>
</div>

<div id="page-actions">
    <?php if ($this->userIsAllowed('Formularium\Api\Adapter\FormAdapter', 'create')): ?>
        <?= $this->hyperlink($this->translate('Add new form'), $this->url(null, ['action' => 'add'], true), ['class' => 'button', 'data-cy' => 'add-new-form']) ?>
    <?php endif; ?>
</div>

<?php $this->trigger('view.browse.before'); ?>
<?php if ($forms): ?>

<table class="tablesaw batch-edit" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?= $this->translate('Name') ?></th>
            <th><?= $this->translate('Submissions') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($forms as $form): ?>
        <tr>
            <td>
                <?= $form->name() ?>

                <ul class="actions">
                    <?php $this->trigger('view.browse.actions', ['resource' => $form]); ?>

                    <?php if ($form->userIsAllowed('update')): ?>
                        <li><?= $form->link('', 'edit', [
                            'class' => 'o-icon-edit',
                            'title' => $this->translate('Edit'),
                        ]); ?></li>
                    <?php endif; ?>

                    <?php if ($form->userIsAllowed('delete')): ?>
                        <li><?= $this->hyperlink('', '#', [
                            'data-sidebar-selector' => '#sidebar',
                            'data-sidebar-content-url' => $form->url('delete-confirm'),
                            'class' => 'o-icon-delete sidebar-content',
                            'title' => $this->translate('Delete'),
                        ]); ?></li>
                    <?php endif; ?>

                    <li><?php echo $this->hyperlink('', '#', [
                        'data-sidebar-selector' => '#sidebar',
                        'data-sidebar-content-url' => $form->url('show-details'),
                        'class' => 'o-icon-more sidebar-content',
                        'title' => $this->translate('Details'),
                    ]); ?></li>
                </ul>
            </td>
            <td><?= $this->hyperlink($form->submissionCount(), $this->url('admin/formularium/form-submission', [], ['query' => ['form_id' => $form->id()]])) ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php $this->trigger('view.browse.after'); ?>
<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<div id="sidebar" class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $this->translate('Close'),
    ]); ?>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>

<div class="no-resources">
    <p><?php echo $this->translate('Omeka could not find any forms.'); ?></p>
</div>

<?php endif; ?>
